#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
}

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\AttackCommand;
use Symfony\Component\Console\Command\CreateCommand;
use Symfony\Component\Console\Command\DownCommand;
use Symfony\Component\Console\Command\StatusCommand;
use Symfony\Component\Console\Command\UpCommand;

$application = new Application();

$application->setName('Hummelflug');

$application->add(new AttackCommand());
$application->add(new CreateCommand());
$application->add(new DownCommand());
$application->add(new UpCommand());
$application->add(new StatusCommand());

$application->run();